import Head from "next/head";
import Header from "@components/Header";
import DefaultLayout from "@components/DefaultLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>rpturbina | Personal Website by Rizki Pratama Turbina</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="description"
          content="Hello World👋! I'm Rizki Pratama Turbina. Frontend Web Enthusiast | Bring my frontend experiences to solve your problems."
        />
      </Head>

      <DefaultLayout>
        <h1>Hello World!</h1>
      </DefaultLayout>
    </>
  );
}
